version: '3.4'

services:
  catalogdb: 
    container_name: catalogdb
    restart: always
    ports: 
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
  
  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
